version: '3.8'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: "YourPassword123"
      MSSQL_USER: "YourUsername"
      MSSQL_PASSWORD: "YourPassword123"
    ports:
      - "1433:1433"
    networks:
      - your_network_name

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mssql-server
    networks:
      - your_network_name

networks:
  your_network_name:
    driver: bridge